"""

Revision ID: 8a3893580973
Revises: f8d9f3807159
Create Date: 2026-02-03 23:16:18.203563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3893580973'
down_revision: Union[str, Sequence[str], None] = 'f8d9f3807159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False, postgresql_using='id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
