"""

Revision ID: bb4f1b77ef38
Revises: 8a3893580973
Create Date: 2026-02-03 23:31:28.480893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4f1b77ef38'
down_revision: Union[str, Sequence[str], None] = '8a3893580973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usercredentials', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    op.create_index(op.f('ix_usercredentials_user_id'), 'usercredentials', ['user_id'], unique=False)
    op.create_foreign_key(None, 'usercredentials', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usercredentials', type_='foreignkey')
    op.drop_index(op.f('ix_usercredentials_user_id'), table_name='usercredentials')
    op.alter_column('usercredentials', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
